name = "sciada"
description = "Collection of Scientific Operations"
version = "0.1.0"
long-description = """


"""

authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
licenses = "Apache-2.0"
website = "https://gitlab.com/stcarrez/ada-sci"
tags = ["sci", "scientific"]

[gpr-externals]
SCIADA_BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
SCIADA_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

[configuration]
disabled = true

[origin]
commit = "517a8b4293ba97931ee8e026a6226766955a5da6"
url = "git+https://gitlab.com/stcarrez/ada-sci.git"

