name = "printer_toolkitada"
description = "Printer toolkit to write reports"
version = "0.2.0"
long-description = """

"""

authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
licenses = "Apache-2.0"
website = "https://gitlab.com/stcarrez/printer-toolkit"
tags = ["i18n", "nls", "bindings"]

[gpr-externals]
PT_BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
PT_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

[configuration]
disabled = true

[[depends-on]]
ansiada = "^1.0.0"

[origin]
commit = "9e5291a2803f6109a3ba06e0cbb9eb1cbe919977"
url = "git+https://gitlab.com/stcarrez/printer-toolkit.git"

